basePath: /
host: localhost:8080
info:
  contact: {}
  description: API for LearningSides
  title: LearningSides
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
